sonata_media:
    db_driver: doctrine_orm
    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    default_context: default

    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        accueil:
            providers:
                - sonata.media.provider.image
            formats:
                banniere1: { width: 1520 , height: 420 , quality: 70}
                banniere2: { width: 1520 , height: 500 , quality: 70}

        partenaire:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 158 , height: 58 , quality: 70}

        temoignage:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 80 , height: 80 , quality: 70}

        equipe:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 360 , height: 300 , quality: 70}

        banauxi:
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 1520 , height: 290 , quality: 70}
                
        service:
            providers:
                - sonata.media.provider.image
            formats:
                banniere: { width: 1520 , height: 290 , quality: 70, }
                image: { width: 847 , height: 456 , quality: 70,  }
                
        propos:
            providers:
                - sonata.media.provider.image
            formats:
                photo: { width: 555 , height: 370 , quality: 70, }
                image: { width: 555 , height: 277 , quality: 70,  }

    cdn:
        server:
            path: /soshome/public/upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false
