sonata_admin:
    title: 'SOSHOME'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.configuration:
                label: "Administration"
                label_catalogue: SOSHOME
                icon: '<i class="fa fa-cog"></i>'
                items:
                    - admin.temoignage
                    - admin.partenaire
                    - admin.accueil
                    - admin.contact
                    - admin.newsletter
                    - admin.message
                    - admin.equipe
                    - admin.service
                    - admin.about
                    - admin.brand_ambassador
                    - admin.brand
                    - admin.propos




sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
