<?php

namespace App\Application\Sonata\MediaBundle\Entity;

use App\Entity\Accueil;
use App\Entity\Temoignage;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Temoignage", mappedBy="image", cascade={"persist", "remove"})
     */
    private $temoignage;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Accueil", mappedBy="banniere1", cascade={"persist", "remove"})
     */
    private $banniere2;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Accueil", mappedBy="banniere3", cascade={"persist", "remove"})
     */
    private $accueil;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getTemoignage(): ?Temoignage
    {
        return $this->temoignage;
    }

    public function setTemoignage(Temoignage $temoignage): self
    {
        $this->temoignage = $temoignage;

        // set the owning side of the relation if necessary
        if ($this !== $temoignage->getImage()) {
            $temoignage->setImage($this);
        }

        return $this;
    }

    public function getBanniere2(): ?Accueil
    {
        return $this->banniere2;
    }

    public function setBanniere2(?Accueil $banniere2): self
    {
        $this->banniere2 = $banniere2;

        // set (or unset) the owning side of the relation if necessary
        $newBanniere1 = $banniere2 === null ? null : $this;
        if ($newBanniere1 !== $banniere2->getBanniere1()) {
            $banniere2->setBanniere1($newBanniere1);
        }

        return $this;
    }

    public function getAccueil(): ?Accueil
    {
        return $this->accueil;
    }

    public function setAccueil(?Accueil $accueil): self
    {
        $this->accueil = $accueil;

        // set (or unset) the owning side of the relation if necessary
        $newBanniere3 = $accueil === null ? null : $this;
        if ($newBanniere3 !== $accueil->getBanniere3()) {
            $accueil->setBanniere3($newBanniere3);
        }

        return $this;
    }
}
