<?php

namespace App\Application\Sonata\MediaBundle\Entity;

use App\Entity\Temoignage;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Temoignage", mappedBy="image", cascade={"persist", "remove"})
     */
    private $temoignage;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getTemoignage(): ?Temoignage
    {
        return $this->temoignage;
    }

    public function setTemoignage(Temoignage $temoignage): self
    {
        $this->temoignage = $temoignage;

        // set the owning side of the relation if necessary
        if ($this !== $temoignage->getImage()) {
            $temoignage->setImage($this);
        }

        return $this;
    }
}
